<?php

// improve related posts
function improve_related_posts($results)
{
	// always keep the first result, being "most relevant"
	$output = array(
		array_shift($results)
	);

	// next, look up the title for each of the remaining items
	$items = array();

	foreach ($results as $result) {
		$title = get_the_title($result->ID);

		if (strpos(strtolower($title), 'part 2') === false) {
			// not a second part, add to items
			$items[] = $result;
		}
	}

	// results will be in order of their preference, let’s just keep the top
	// four results here
	$items = array_slice($items, 0, 4);

	// now let's randomize the order of these
	shuffle($items);

	// since we only want 2 posts total, and already have 1, just get the first one
	$output[] = array_shift($items);

	// finally, return that set
	return $output;
}

add_filter('get_crp_posts_id', 'improve_related_posts');



// randomize related posts
function randomize_related_posts($orderby, $source_post)
{
	return 'RAND()';
}


// //markswinimer : removes empty <p> tags generated by wpautop and more
//
// //add_filter('crp_posts_orderby', 'randomize_related_posts');
// /**
//  * Remove empty paragraphs created by wpautop()
//  * @author Ryan Hamilton
//  * @link https://gist.github.com/Fantikerz/5557617
//  */
// function remove_empty_p( $content ) {
// 	$content = force_balance_tags( $content );
// 	$content = preg_replace( '#<p>\s*+(<br\s*/*>)?\s*</p>#i', '', $content );
// 	$content = preg_replace( '~\s?<p>(\s| )+</p>\s?~', '', $content );
// 	return $content;
// }
// add_filter('the_content', 'remove_empty_p', 20, 1);
//
// //markswinimer : additionaly removes empty <p> tags by removing wpautop
remove_filter('the_content', 'wpautop');
